version: '3.8'

services:
  report-generation:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pharmacopilot-reports
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ANONYMIZED_TELEMETRY=False
      - CHROMA_TELEMETRY=False
      - API_BASE_URL=http://localhost:8000
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - pharmacopilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/reports/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - prediction-api

  # Reference to the existing prediction API
  prediction-api:
    image: placeholder
    container_name: pharma-ml-api
    ports:
      - "8000:8000"
    networks:
      - pharmacopilot-network
    profiles:
      - external  # This won't start automatically

networks:
  pharmacopilot-network:
    driver: bridge
    name: pharmacopilot-network
